import { SoldPrice } from '@/../types/sold-price';

export const mockSoldPrices: SoldPrice[] = [
  {
    id: 'MOCK-1',
    price: 350000,
    dateOfTransfer: '2023-10-26',
    postcode: 'SS9 1AA',
    propertyType: 'T',
    old_new: 'N',
    duration: 'F',
    paon: '10',
    saon: '',
    street: 'LEIGH ROAD',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-2',
    price: 450000,
    dateOfTransfer: '2023-09-15',
    postcode: 'SS9 1AB',
    propertyType: 'S',
    old_new: 'N',
    duration: 'F',
    paon: '22',
    saon: 'FLAT 1',
    street: 'BROADWAY',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-3',
    price: 620000,
    dateOfTransfer: '2023-08-01',
    postcode: 'SS9 1AC',
    propertyType: 'D',
    old_new: 'N',
    duration: 'F',
    paon: '1',
    saon: '',
    street: 'CLIFF PARADE',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-4',
    price: 280000,
    dateOfTransfer: '2023-07-20',
    postcode: 'SS9 1AD',
    propertyType: 'F',
    old_new: 'Y',
    duration: 'L',
    paon: 'THE GRAND',
    saon: 'APARTMENT 50',
    street: 'THE PARADE',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-5',
    price: 510000,
    dateOfTransfer: '2022-11-05',
    postcode: 'SS9 1AA',
    propertyType: 'S',
    old_new: 'N',
    duration: 'F',
    paon: '12A',
    saon: '',
    street: 'LEIGH ROAD',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-6',
    price: 780000,
    dateOfTransfer: '2022-10-18',
    postcode: 'SS9 1AC',
    propertyType: 'D',
    old_new: 'N',
    duration: 'F',
    paon: '2',
    saon: '',
    street: 'CLIFF PARADE',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-7',
    price: 315000,
    dateOfTransfer: '2022-06-22',
    postcode: 'SS9 1AD',
    propertyType: 'F',
    old_new: 'N',
    duration: 'L',
    paon: 'THE GRAND',
    saon: 'APARTMENT 32',
    street: 'THE PARADE',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-8',
    price: 850000,
    dateOfTransfer: '2023-12-01',
    postcode: 'SE3 0EU',
    propertyType: 'T',
    old_new: 'N',
    duration: 'F',
    paon: '15',
    saon: '',
    street: 'MONTPELIER ROW',
    locality: 'BLACKHEATH',
    town_city: 'LONDON',
    county: 'GREATER LONDON',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-9',
    price: 1200000,
    dateOfTransfer: '2023-11-20',
    postcode: 'SE3 7BT',
    propertyType: 'S',
    old_new: 'N',
    duration: 'F',
    paon: '2',
    saon: '',
    street: 'THE ORCHARD',
    locality: 'BLACKHEATH',
    town_city: 'LONDON',
    county: 'GREATER LONDON',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-10',
    price: 650000,
    dateOfTransfer: '2023-10-05',
    postcode: 'SE3 9RL',
    propertyType: 'F',
    old_new: 'Y',
    duration: 'L',
    paon: '40',
    saon: 'FLAT 3',
    street: 'KIDBROOKE GROVE',
    locality: 'KIDBROOKE',
    town_city: 'LONDON',
    county: 'GREATER LONDON',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-11',
    price: 975000,
    dateOfTransfer: '2022-05-12',
    postcode: 'SE3 0EU',
    propertyType: 'T',
    old_new: 'N',
    duration: 'F',
    paon: '16',
    saon: '',
    street: 'MONTPELIER ROW',
    locality: 'BLACKHEATH',
    town_city: 'LONDON',
    county: 'GREATER LONDON',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-12',
    price: 1350000,
    dateOfTransfer: '2022-04-28',
    postcode: 'SE3 7BT',
    propertyType: 'S',
    old_new: 'N',
    duration: 'F',
    paon: '3',
    saon: '',
    street: 'THE ORCHARD',
    locality: 'BLACKHEATH',
    town_city: 'LONDON',
    county: 'GREATER LONDON',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-13',
    price: 210000,
    dateOfTransfer: '2024-01-15',
    postcode: 'M1 1AD',
    propertyType: 'F',
    old_new: 'Y',
    duration: 'L',
    paon: 'WHITWORTH LOCKE',
    saon: 'APARTMENT 101',
    street: 'WHITWORTH STREET WEST',
    locality: '',
    town_city: 'MANCHESTER',
    county: 'GREATER MANCHESTER',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-14',
    price: 320000,
    dateOfTransfer: '2023-11-08',
    postcode: 'M1 5AN',
    propertyType: 'F',
    old_new: 'N',
    duration: 'L',
    paon: 'THE HACIENDA',
    saon: 'APARTMENT 205',
    street: 'WHITWORTH STREET WEST',
    locality: '',
    town_city: 'MANCHESTER',
    county: 'GREATER MANCHESTER',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-15',
    price: 180000,
    dateOfTransfer: '2023-09-30',
    postcode: 'M1 2WA',
    propertyType: 'F',
    old_new: 'N',
    duration: 'L',
    paon: 'INDIA HOUSE',
    saon: 'FLAT 5',
    street: 'WHITWORTH STREET',
    locality: '',
    town_city: 'MANCHESTER',
    county: 'GREATER MANCHESTER',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-16',
    price: 450000,
    dateOfTransfer: '2023-07-11',
    postcode: 'M1 4DY',
    propertyType: 'T',
    old_new: 'N',
    duration: 'F',
    paon: '12',
    saon: '',
    street: 'CHORLTON STREET',
    locality: '',
    town_city: 'MANCHESTER',
    county: 'GREATER MANCHESTER',
    ppd_category_type: 'A',
    record_status: 'A',
  },
];

export const mockTrendData = [
  { year: '2021', avgPrice: 380000, pctChange: null },
  { year: '2022', avgPrice: 410000, pctChange: 7.9 },
  { year: '2023', avgPrice: 425000, pctChange: 3.7 },
  { year: '2024', avgPrice: 440000, pctChange: 3.5 },
]; 