import { SoldPrice } from '@/../types/sold-price';

export const mockSoldPrices: SoldPrice[] = [
  {
    id: 'MOCK-1',
    price: 350000,
    date_of_transfer: '2023-10-26',
    postcode: 'SS9 1AA',
    property_type: 'T',
    old_new: 'N',
    duration: 'F',
    paon: '10',
    saon: '',
    street: 'LEIGH ROAD',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-2',
    price: 450000,
    date_of_transfer: '2023-09-15',
    postcode: 'SS9 1AB',
    property_type: 'S',
    old_new: 'N',
    duration: 'F',
    paon: '22',
    saon: 'FLAT 1',
    street: 'BROADWAY',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-3',
    price: 620000,
    date_of_transfer: '2023-08-01',
    postcode: 'SS9 1AC',
    property_type: 'D',
    old_new: 'N',
    duration: 'F',
    paon: '1',
    saon: '',
    street: 'CLIFF PARADE',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
  {
    id: 'MOCK-4',
    price: 280000,
    date_of_transfer: '2023-07-20',
    postcode: 'SS9 1AD',
    property_type: 'F',
    old_new: 'Y',
    duration: 'L',
    paon: 'THE GRAND',
    saon: 'APARTMENT 50',
    street: 'THE PARADE',
    locality: 'LEIGH-ON-SEA',
    town_city: 'SOUTHEND-ON-SEA',
    county: 'ESSEX',
    ppd_category_type: 'A',
    record_status: 'A',
  },
];

export const mockTrendData = [
  { year: '2021', avgPrice: 380000, pctChange: null },
  { year: '2022', avgPrice: 410000, pctChange: 7.9 },
  { year: '2023', avgPrice: 425000, pctChange: 3.7 },
]; 